### ISSUE TITLE
add command to remove quotes 

### ISSUE THREAD

**Issue by twf9097** [OneTrueBen/pa-discordbot#12]
there is command to add quotes but no command to remove one

**Comment by OneTrueBen** [comment]
very fair -- but i will hold off until we can ban people who are not mods from using any command

**Comment by twf9097** [comment]
non mods can currenly use all commands?
if so possibly make it so afterwords we add authenticaten people can remove their own quotes

**Comment by OneTrueBen** [comment]
yeah, it's kind of wild.

**Comment by OneTrueBen** [comment]
permissions are here. not blocked anymore

**Comment by OneTrueBen** [comment]
done
