### ISSUE TITLE
needs timed-mutes

### ISSUE THREAD

**Issue by OneTrueBen** [OneTrueBen/pa-discordbot#6]
i want to be able to mute people for a certain amount of time

**Comment by OneTrueBen** [comment]
i am trying the dev build and the feature doesn't seem to work @benjjs 
![image](https://user-images.githubusercontent.com/1869526/91781868-75786600-ebc9-11ea-8b3a-2cc4ceef99c4.png)

**Comment by benjjs** [comment]
Implemented
